name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Format code
      run: npm run format

    - name: Run tests
      run: npm test

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #   - name: Deploy to EC2
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.EC2_HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       port: ${{ secrets.EC2_PORT }}
  #       script: |
  #         cd ${{ secrets.TARGET_DIR}}
  #         git pull
  #         npm install
  #         npm run start
